name: Terraform Action for AWS

inputs:
  directory:
    description: 'Directory of the Terraform configuration'
    required: true
  variables:
    description: 'Variables to pass to Terraform'
    required: false
  workspace:
    description: 'Terraform workspace'
    required: false
  aws-region:
    description: 'AWS Region'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true

runs:
  using: "composite"
  steps:
  - name: Print Where I AM
    run: pwd
    shell: bash

  - name: Print Directory Structure
    run: ls -al ./
    shell: bash

  - name: Login to AWS
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
      aws-region: ${{ inputs.aws-region }}

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3
    with:
    terraform_version: 1.9.1

  - name: Terraform Init
    run: terraform init -upgrade
    shell: bash

  - name: Terraform Validate
    env:
      TF_VAR_region: ${{ inputs.aws_region }}
    run: |
      terraform validate
    shell: bash

  - name: Terraform Plan
    env:
      TF_VAR_region: ${{ inputs.aws_region }}
    run: |
      terraform plan
    shell: bash

  # - name: Terraform Apply
  #   env:
  #     TF_VAR_region: ${{ inputs.aws_region }}
  #   run: |
  #     terraform apply -auto-approve
  #   shell: bash
