name: Docker Action - Build and push to docker Hub
description: Build and push docker image to docker Hub

inputs:
  image-name:
    description: Name of the Docker image
    required: true
  image-tag:
    description: Tag of the Docker image
    required: true
  directory:
    description: 'Directory of the Dockerfile'
    required: true
  dockerhub-username:
    description: 'DockerHub username'
    required: true
  dockerhub-token:
    description: 'DockerHub token'
    required: true

runs:
  using: "composite"
  steps:
  - name: Print Where I AM
    run: pwd
    shell: bash

  - name: Print Directory Structure
    run: ls -al ./
    shell: bash

  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ inputs.dockerhub-username }}
      password: ${{ inputs.dockerhub-token }}

  - name: Build and push docker image
    run: |
      docker build --platform linux/x86_64,linux/amd64,linux/arm64 -t ${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.directory }}
      docker push ${{ inputs.image-name }}:${{ inputs.image-tag }}
    shell: bash
