name: Build Project

inputs:
  test:
    default: "yes"
    description: "Run tests?"
    required: false

runs:
  using: "composite"
  steps:
  - name: Print Where I AM
    run: pwd
    shell: bash

  - name: Set up JDK
    uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: '21'

  - name: mvn clean
    run: mvn clean
    shell: bash

  - name: mvn package
    run: |
      if [[ "${{ inputs.test }}" == "no" ]]; then
        echo "Skipping tests"
        mvn package -Dmaven.test.skip
      else
        mvn package
      fi
    shell: bash
