name: Build npm project
description: Build vite project with Node.js 20

inputs:
  test:
    default: "yes"
    description: "Run tests?"
    required: false
  working-directory:
    description: working directory
    required: true

runs:
  using: "composite"
  steps:
  - name: Print Where I AM
    run: pwd
    shell: bash

  - name: Set up Node
    uses: actions/setup-node@v4
    with:
      node-version: 20

  - name: npm install
    run: |
      cd ${{ inputs.working-directory }}
      npm install
    shell: bash

  - name: npm run build
    run: |
      cd ${{ inputs.working-directory }}
      npm run build
    shell: bash
