name: Build npm project

inputs:
  test:
    default: "yes"
    description: "Run tests?"
    required: false
  directory:
    description: working directory
    required: true

runs:
  using: "composite"
  steps:
  - name: Print Where I AM
    run: pwd
    shell: bash

  - name: Set up Node
    uses: actions/setup-node@v4
    with:
      node-version: 18

  - name: npm install
    run: |
      cd ${{ inputs.directory }}
      npm install
    shell: bash

  - name: npm run build
    run: |
      cd ${{ inputs.directory }}
      npm run build
    shell: bash
